### ISSUE TITLE
broker.id should also be set in $logs_dir/meta.properties

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-kafka#117]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: any
- Ruby: any
- Distribution: any
- Module version: <= 2.1.0

### What are you seeing

When `kafka::broker::config`'s `broker.id` changes that change is not reflected in `$log_dir`'s `meta.properties`. This causes kafka startup to fail (see below)

### What behaviour did you expect instead

Dynamic environments are… well… dynamic. An integer such as a `broker.id` can easily be changed for any number of reasons. Our module should enable and support this.

### Output log

```
[2016-11-18 13:25:28,078] INFO Logs loading complete. (kafka.log.LogManager)
[2016-11-18 13:25:28,130] INFO Starting log cleanup with a period of 300000 ms. (kafka.log.LogManager)
[2016-11-18 13:25:28,131] INFO Starting log flusher with a default period of 9223372036854775807 ms. (kafka.log.LogManager)
[2016-11-18 13:25:28,138] FATAL Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.common.InconsistentBrokerIdException: Configured broker.id 3 doesn't match stored broker.id 1 in meta.properties. If you moved your data, make sure your configured broker.id matches. If you intend to create a new broker, you should remove all data in your data directories (log.dirs).
        at kafka.server.KafkaServer.getBrokerId(KafkaServer.scala:648)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:187)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:37)
        at kafka.Kafka$.main(Kafka.scala:67)
        at kafka.Kafka.main(Kafka.scala)
[2016-11-18 13:25:28,140] INFO shutting down (kafka.server.KafkaServer)
```
### Any additional information you'd like to impart

I don't know how to guarantee the uniqueness of this number across a cluster, since in puppet we have no easy way to know who's part of a cluster.

Zookeeper would be a way? maybe??

**Comment by dhoppe** [comment]
@igalic The `broker.id` should never change and somehow you need to make sure that it is unique. In my case I use an AWS EC2 tag as fact to provide a unique `broker.id`. 

I do not know what you mean by _dynamic environments_, because I have not seen an environment where you scale up/out Kafka nodes. 

If you need this you might want to take a look at AWS Kinesis Firehose.

**Comment by igalic** [comment]
i think i've finally understood that my implementation is wrong, in that it needs to go the other way around.

**Comment by igalic** [comment]
update: i have now tested `broker.id=-1` and it just works™

i can change the `broker.id` *to* `-1` and it will just pick up what's there in `metadata.properties` and work.
